enable group members binding
bitmark-inc/autonomy-pod-controller pull request #7
Opened 2021-05-05 09:49 UTC by nodestory

2021-05-06 02:40 UTC, lemonlatte requested changes

2021-05-06 02:40 UTC, lemonlatte commented on acl.go
> +		return mode > AccessModeNotApplicant && mode <= AccessModeMinimal
Using comparison is implicit and causes some confusion and if someone adds incorrect `AccessMode` in between, the access control would be failed.

I think a better way would be using bitwise operations or create a list of allowance.

2021-05-07 02:50 UTC, lemonlatte approved these changes
LGTM

2021-05-10 01:16 UTC, hxw approved these changes

2021-05-11 03:50 UTC, merged